[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' rocketlabdelta.com; style-src 'self'; worker-src 'self'; script-src 'self' 'unsafe-inline' 'sha256-U89QW7WEfHqChRBO1QQA2ihdvdpJmlS0DFKYxqcQozE=' 'sha256-EvYfle4RtIAucIPnV5wMS/MEWRBXx08q7iWWALXoHjc='; object-src 'none'; base-uri 'none';"
